package utils;

public enum LogAction {
    ADD_EMPLOYEE,
    UPDATE_EMPLOYEE,
    DELETE_EMPLOYEE,
    ADD_CATEGORY,
    UPDATE_CATEGORY,
    DELETE_CATEGORY,
    ADD_PRODUCT,
    UPDATE_PRODUCT,
    DELETE_PRODUCT,
    ADD_PRODUCT_TO_STORE,
    UPDATE_PRODUCT_IN_STORE,
    DELETE_PRODUCT_IN_STORE,
    ADD_CUSTOMER_CARD,
    UPDATE_CUSTOMER_CARD,
    DELETE_CUSTOMER_CARD,
    ADD_CHECK,
    DELETE_CHECK,
    ADD_SALE,
    DELETE_SALE,
    LOGIN,
    CHANGE_PASSWORD,
    PRINT
}
